# Terminology
# -----------
# 1  session (each is displayed by a client, all are managed by a server)
# 1+ windows
# 1+ panes (pseudo terminals)

# Change the default prefix key
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Configure a session with 2 windows
new-session

new-window -c ~/Code/MC/maplecroft-vm -n 'shell'
split-window -c ~/Code/MC/maplecroft-vm -v -p 50

new-window -c ~/Code/MC/maplecroft -n 'git'
split-window -c ~/Code/MC/maplecroft -h -p 50
