# Terminology
# -----------
# 1  session (each is displayed by a client, all are managed by a server)
# 1+ windows
# 1+ panes (pseudo terminals)

# Change the default prefix key
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Configure a session with 1 window and 3 panes
new-session
new-window
split-window -v -p 25 -t 0
split-window -h -p 50 -t 0
