source-file ~/.tmux.conf

# runserver window
new-session -s django -n runserver
send-keys -t django 'cd $TMUX_HOME' C-m

# git window
new-window -n git -t django
send-keys -t django 'cd $TMUX_HOME' C-m
split-window -h -t django
send-keys -t django:2.1 'git branch' C-m

# shell window
new-window -n shell -t django
send-keys -t django 'cd $TMUX_HOME' C-m
