source-file ~/.tmux.conf

# flask
new-session -s nessie -n flask
send-keys -t nessie:1.1 'cd /home/iain/Code/annotator-store' C-m
send-keys -t nessie:1.1 'vex annotator-store python run.py' C-m

# django
new-window -n django -t nessie
send-keys -t nessie:2.1 'cd /home/iain/Code/nessie' C-m
send-keys -t nessie:2.1 'vex nessie python manage.py runserver 127.0.0.1:8000' C-m

# tox
new-window -n tox -t nessie
send-keys -t nessie:3.1 'cd /home/iain/Code/nessie' C-m
send-keys -t nessie:3.1 'while true; do inotifywait -r -q -e move -e modify -e create -e delete -e close_write --exclude="[^p][^y]$" .; vex nessie tox; done' C-m

# git
new-window -n git -t nessie
split-window -h -t nessie
send-keys -t nessie:4.1 'cd /home/iain/Code/nessie' C-m
send-keys -t nessie:4.1 'git branch' C-m
send-keys -t nessie:4.2 'cd /home/iain/Code/nessie' C-m
send-keys -t nessie:4.2 'git pull' C-m

# shell
new-window -n shell -t nessie
send-keys -t nessie:5.1 'workon nessie' C-m

# return to django
select-window -t nessie:2
