user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
}

http {
    include /etc/nginx/mime.types;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    upstream metabase {
        server 127.0.0.1:3000;
    }

    upstream nessie {
        server 127.0.0.1:8000;
    }

    upstream unicef {
        server 127.0.0.1:8010;
    }

    upstream heimdall {
        server 127.0.0.1:8020;
    }

    server {
        listen 3030;

        access_log /var/log/nginx/metabase-access.log;
        error_log /var/log/nginx/metabase-error.log;

        location / {
            proxy_pass http://metabase;
        }
    }

    server {
        listen 443 ssl;
        server_name nessie.maplecroft.test;
        root /home/idillingham/Code/nessie;
        ssl_certificate /usr/local/share/ca-certificates/dev.maplecroft.crt;
        ssl_certificate_key /usr/local/share/ca-certificates/dev.maplecroft.key;

        location / {
            proxy_pass http://nessie;
        }
    }

    server {
        listen 80;
        server_name unicef.maplecroft.test;
        root /home/idillingham/Code/unicef;

        location / {
            proxy_pass http://unicef;
        }
    }

    server {
        listen 80;
        server_name heimdall.maplecroft.test;
        root /home/idillingham/Code/heimdall;

        location / {
            proxy_pass http://heimdall;
        }
    }
}
