set-option -g prefix C-a
unbind-key C-b

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind-key Left
unbind-key Down
unbind-key Up
unbind-key Right

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set-window-option -g mode-keys vi

bind C-s set-window-option synchronize-panes

set-option -g base-index 1
set-window-option -g pane-base-index 1

bind | split-window -h
bind - split-window -v

bind C-c run "tmux save-buffer - | xclip -i -sel clipboard"
bind C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"

bind r source-file ~/.tmux.conf \; display "Reloaded the configuration"

set -g status-utf8 on
set -g status-left "#S"
set -g status-right ""
