set-option -g prefix C-a
unbind-key C-b
bind C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind-key Left
unbind-key Down
unbind-key Up
unbind-key Right

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r r source-file "${HOME}/.config/tmux/tmux.conf" \; display 'Reloaded configuration'

set -g default-terminal 'xterm-256color'

set-window-option -g mode-keys vi

set-option -g base-index 1
set-window-option -g pane-base-index 1

bind | split-window -h
bind - split-window -v

set -g status-left "#S"
set -g status-right ""

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @colors-solarized 'dark'

run "${HOME}/.tmux/plugins/tpm/tpm"
