# Key bindings
########################################################################################
bind-key r source-file "${HOME}/.config/tmux/tmux.conf" \; display 'Reloaded configuration'

# prefix key
set-option -g prefix C-a
bind-key C-a send-prefix
unbind-key C-b

# splitting windows
bind-key | split-window -h
bind-key - split-window -v

# selecting panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

unbind-key Left
unbind-key Down
unbind-key Up
unbind-key Right

# resizing panes
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# Options
########################################################################################
set-option -g allow-passthrough on
set-option -g default-terminal "screen-256color"
set-option -g escape-time 10
set-option -g focus-events on
set-window-option -g mode-keys vi

# indexes
set-option -g base-index 1
set-window-option -g pane-base-index 1

# status
set-option -g status-left ""
set-option -g status-right "#{session_name}"
set-option -g window-status-format "#{window_index}:#{window_name}"
set-option -g window-status-current-format "#{window_index}:#{window_name}*"
